name: Eventos
run-name: Ejecucion con valores fail ${{inputs.fail}}
on:       
   workflow_dispatch: 
    inputs:  
      Tag:
        description: Tag to Deploy
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v1
        
      entorno:
        type: environment
        description: Entorno de despliegue

          
  
env:
  VARIABLE_TEST: "Hola"
  VARIABLE_TEST2: ${{12.2}}


jobs:
  job1: 
    env:
      VARIABLE_TEST: "hola job1"
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo "hola mundo, fui lanzado por el evento ${{github.event_name}}  " 
    
      - name: Execute process fail  
        run: | 
           exit 1

      - name: Print 2 GoodBye
        if: ${{always()}}
        run: | 
            echo "Siempre me despido Bye World"   
   
  job2: 
    needs: job1
    env:
      VARIABLE_TEST: "hola job2"
    runs-on: ubuntu-latest
    steps: 

      - name: Print  info job1
        run: | 
            echo "Hola mundo"

      - name: Print  GoodBye
        if: ${{always()}}
        run: | 
            echo "Siempre me despido Bye World"   