name: Eventos
run-name: Ejecucion con valores fail ${{inputs.fail}}
on:       
   workflow_dispatch: 
    inputs:  
      fail:
        description: ¿Quieres que falle?
        type: boolean
        default: false

env:
  VARIABLE_TEST: "Hola"
  VARIABLE_TEST2: ${{12.2}}


jobs:
  job: 
    env:
      VARIABLE_TEST: "hola job"
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo "hola mundo, fui lanzado por el evento ${{github.event_name}}  "
    
      - name: Execute process fail
        if: inputs.fail
        run: | 
           exit 1

      - name: Print  info job1
        run: | 
           echo "Hola mundo"

      - name: Print  GoodBye
        if: ${{always()}}
        run: | 
           echo "Siempre me despido Bye World"
      