name: Eventos
run-name: Ejecucion con valores debug-${{inputs.debug}} y tag ${{inputs.tag}}
on:       
   workflow_dispatch: 
    inputs:
      debug: 
        description: ¿Quieres depurar?
        type: boolean
        default: false
      tag:
        description: ¿Tag?
        type: string
        required: true
      fail:
        description: ¿Quieres que falle?
        type: boolean
        default: false

env:
  VARIABLE_TEST: "Hola"
  VARIABLE_TEST2: ${{12.2}}


jobs:
  job1: 
    env:
      VARIABLE_TEST: "hola job"
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo "hola mundo, fui lanzado por el evento ${{github.event_name}}  "
      - name: Print var
        env:
          VARIABLE_TEST: "hola Step"
        run: | 
          echo "Variable VARIABLE_TEST - $VARIABLE_TEST"  
      - name: Print inputs        
        run: | 
          echo "Parametros de entrada debug: ${{inputs.debug}} -  tag: ${{inputs.tag}}"  

      - name: Print debug info  
        if: ${{inputs.debug}}
        run: | 
           echo "DEPURACION"  

      - name: Execute process fail
        if: ${{inputs.fail}}
        run: | 
           exit 1

      - name: Print  info       
        run: | 
           echo "Hola mundo"
      