name: Eventos
run-name: Ejecucion con valores fail ${{inputs.fail}}
on:       
   workflow_dispatch: 
    inputs:  
      tag:
        description: Tag to Deploy
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v1

      entorno:
        type: environment
        description: Entorno de despliegue
          
  
env:
  VARIABLE_TEST: "Hola"
  VARIABLE_TEST2: ${{12.2}}


jobs:
  job1:
    environment: ${{inputs.entorno}}
    outputs:
      TAG: ${{ steps.tagCalculation.outputs.ETIQUETA}}
    env:
      VARIABLE_TEST: "hola job1"
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo "Configurando para user ${{vars.USERNAME}} " 

      - name: Calculate tag
        id: tagCalculation
        run: echo "ETIQUETA=Etiqueta${{inputs.tag}} " >> "$GITHUB_OUTPUT"       

      - name: Print 2 GoodBye
        if: ${{always()}}
        run: | 
            echo "Siempre me despido Bye World"   
            echo "ETIQUETA=null " >> "$GITHUB_OUTPUT" 
   

  job2: 
    needs: job1
    env:
      VARIABLE_TEST: "hola job2"
    runs-on: ubuntu-latest
    steps:       
      - name: Deploy tag
        run: |
            echo "Deploying tag ${{needs.job1.outputs.TAG}}"



     