name: Eventos
run-name: Ejecucion con valores debug-${{inputs.debug}} y tag ${{inputs.tag}}
on:       
   workflow_dispatch: 
    inputs:  
      fail:
        description: ¿Quieres que falle?
        type: boolean
        default: false

env:
  VARIABLE_TEST: "Hola"
  VARIABLE_TEST2: ${{12.2}}


jobs:
  job1:     
    runs-on: ubuntu-latest
    steps:                
      - name: Execute process fail         
        run: | 
            sleep 20

      - name: Print  info job1       
        run: | 
            echo "Hola mundo"
  job2: 
    env:
      VARIABLE_TEST: "hola job"
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo "hola mundo, fui lanzado por el evento ${{github.event_name}}  "
    
      - name: Execute process fail
        if: ${{inputs.fail}}
        run: | 
           exit 1

      - name: Print  info job2     
        run: | 
           echo "Hola mundo"
      