name: adasd
on: pull_request

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.labels) }}
          "======="
          ${{ github.event.pull_request.labels }}
          EOF